### ISSUE TITLE
Keyboard doesn't work for interactive elements

### ISSUE THREAD

**Issue by tajo** [tajo/react-movable#15]
If you place an interactive element (input etc) into the item, you can't control it with keyboard since `space` and other shortcuts are captured by the drag-n-drop navigation.

**Comment by workzer** [comment]
I had to deactivate the space navigation in order to use my form:
`renderItem={({ value, props }) => {
        props.onKeyDown = (e) => { return e };
	return(<li {...props} className={"p-0 list-group-item"}>{value}</li>) 
}}`
Finding another way to deal with interactive forms would be really welcome, like having an agument to set a list of html nodes not touched by the drag and drops navigation system.
For now, the only way to deal with some subevent(as far as I know) is to use native nodes like button, input, textarea, any other node would not trigger any click event.

**Comment by tajo** [comment]
Fixed and released.

**Comment by gpicavet** [comment]
Hello, still facing the problem with a wysiwyg editor using a contenteditable=true (like draft-js).
